version: 0.2

phases:
  install:
    commands:
      # Update package managers
      - sudo apt-get update
      - pip install --upgrade pip

      # Download project build/test requirements
      - pip install --upgrade awscli
      - pip install aws-sam-cli
      - pip install --upgrade jsonschema
      - pip install mock
      - pip install pvapps-odm-dev --extra-index-url https://gy6o8w1na5.execute-api.us-east-1.amazonaws.com/Prod
      

  pre_build:
    commands:
      # Execute all unittests present in Tests/UnitTests
      - python -m unittest discover Tests/UnitTests
  
  build:
    commands:
      # ODM Layer Creation commands
      - mkdir Layers/python
      - pip install pvapps-odm-dev --extra-index-url https://gy6o8w1na5.execute-api.us-east-1.amazonaws.com/Prod -t Layers/python/
      - pip install jsonschema -t Layers/python/
      - cd Layers
      - zip -r pvapps-odm-dev.zip python 
      - cd ..
      # Build Service Template for usage in deployment
      - sam build
      - sam package --template-file template.yml --s3-bucket $S3_BUCKET --output-template trip-calculation.yml
      
artifacts:
  secondary-artifacts:
    template_artifact:
      files:
        - trip-calculation.yml
    integration_test_artifact:
      files:
        - 'Tests/IntegrationTests/*'
      discard-paths: yes
  
